### ISSUE TITLE
Chat Log View

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#12]
**Description**
As a user, I want to have a _chat log_ view so I can see my previous chat history.

**Tasks**
- [x] Create a Chat Log page design
- [x] Have a Settings page design #14 
- [x] Implement settings button to redirect user to Settings page

**Acceptance Criteria**
1. Design should match the chat log view in the wireframe
2. Add a settings button - Implement the settings button to take you to the settings page
3. Add a floating action button for adding a new conversation
4. Placeholder for username (and photo)

Given that a user is on the chat log view, once a user clicks the gear icon for _settings_, they are redirected to the settings page.

![Image](https://user-images.githubusercontent.com/63757643/193414402-35f9b282-3208-4dcb-90d3-3f92d25ff3fd.png)
