### ISSUE TITLE
Conversation View

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#13]
**Description**
As a user, I want to have a _conversation_ view so that I can see a conversation with a specific friend.

**Tasks**
- [x]  Create a conversation page design
- [x] Have a Chat Log page design #12 
- [x]  Implement back button to redirect user back to chat log

**Acceptance Criteria**

1. Design should match the wireframe
2. Show the username (and profile picture) of recipient at the top of the screen
3. Create and implement a back button to go back to chat log
4. Create a text field for the actual message to be sent
5. Create a send button

![Image](https://user-images.githubusercontent.com/63757643/193414566-bfa8abd1-624e-4027-b57c-ee145b618b6c.png)
