### ISSUE TITLE
Settings View

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#14]
**Description**
As a user, I want to have a _settings_ view so that I can change my profile picture and password.

**Tasks**
- [x]  Create a Settings page design
- [x] Have a Chat Log page design #12 
- [x]  Implement back button to redirect user back to chat log

**Acceptance Criteria**

1. Design should match the wireframe settings page
2. Create a back button - Implement the back button to go back to the chat log
3. Create a profile picture icon
4. Create a "change profile picture" button 
5. Create "change password" button

![Image](https://user-images.githubusercontent.com/63757643/193414748-8030307e-4cae-4521-b640-51537a1cb68f.png)
