### ISSUE TITLE
Friend Search View

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#15]
**Description**
As a user, I want to have a _friend search_ view so that I can start a conversation and be redirected to the conversation view.

**Tasks**

- [x] Create a Friend Search page design
- [x] Have a Chat Log page design #12 
- [x] Implement back button to redirect user back to chat log

**Acceptance Criteria**
1. Design should match the wireframe
2. Create a start conversation button
3. Create a search field
4. Create a search button
5. Create a back button
6. Implement the back button to take you to the chat log

![Image](https://user-images.githubusercontent.com/63757643/193414655-040f3153-2de6-4bf8-a3c8-a17153fe7faa.png)
