### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#19]
**Description**
As a user, I want to login and be redirected to the chat log view so that I can view my chat history.

**Tasks**

- [x] Set up database and connect database to the project #18 
- [x] Have a login page design #10 
- [x] Set up authentication communication API between the frontend and the backend
- [x] Have a redirection to the chat log once the user logged in

**Acceptance Criteria**

1. Email and password should be authenticated
2. Once authenticated, user is redirected to the chat log
3. If the email and password is incorrect, a warning will show.

Given that a user is on the login page, once the user clicks the _login_ button, they are redirected to the chat log view.
