### ISSUE TITLE
Add Conversation

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#27]
**Description**
As a user, I want to start a new conversation so that I can chat with another friend.

**Tasks**
- [x] Return user not found if email doesn't exist in our database
- [x] Display user's info if found
- [x] Display a chat now button that redirects to a conversation view with that user
- [x] Populate chat log with this new conversation #37 

**Acceptance Criteria**
- If the username is not found, a toast will appear showing the user does not exist.
- If the username is found, the user's info is displayed.
