### ISSUE TITLE
Conversation

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#33]
**Description**
As a user, I want to be able to send and receive messages so that I can have a conversation with my friend.

**Tasks**

- [x] Display friend information on action bar
- [ ] Load incoming messages and display in chat bubbles
- [x] Send outgoing messages to that user's friend and display in chat bubbles

**Acceptance Criteria**
- If the user is on the conversation view, the messages that the user has received and sent should be displayed.
- If the user is on the conversation view, the username of the person they are currently chatting with will be displayed at the top.
- If a user sends a message, the new message will be sent to the friend, displayed in the conversation view, and the textbox will be cleared.

**Comment by sjiang1** [comment]
Add the following acceptance criteria:
- If a user sends a message, the new message will be sent to the friend, displayed in the conversation view, and the textbox will be cleared.
