### ISSUE TITLE
Settings Change Password

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#36]
**Description**
As a user, I want to be able to change my password so that I can secure my account.

**Tasks**
- [x] Create change password button
- [x] Implement firebase authorization password update
- [x] Text field for current password
- [x] Forgot Password field #63 
- [x] Text field for new password
- [x] Text field for new password again
- [x] Implement an Update Password button

**Acceptance Criteria**
-If the user enters the correct current password, and the new password is valid, the user’s password will be changed to the new password after clicking the Update Password button.
-Once the password is updated successfully, the user will get a message and be redirected to the settings page.
-If the user enters an incorrect current password, there will be a warning.
-If the user enters an invalid new password, there will be a warning.
-The user can click the "forgot password" button for instructions when they forget passwords.
