### ISSUE TITLE
Settings ProPic

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#60]
**Description**
As a user, I want to set a profile picture so that I can express myself.

**Tasks**

- [x] Create option to upload one photo at a time
- [x] Set that photo to user's profile photo
- [x] Set the default profile picture to a silhouette

**Acceptance Criteria**
- If the user clicks the "change photo" button, they will have the option to upload a new picture.

**Comment by sjiang1** [comment]
Add the following acceptance criteria:
- The user can cancel the “change photo” before uploading a new picture.
- Once the photo is uploaded, the settings page will show the new profile photo.
