### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by alimo4** [COSC481W-2022Fall/capstone-project-vibe#61]
**Description**
This is a placeholder for any design changes we decide to make.

**Tasks**

- [x] Change background to agreed upon selection
- [x] Change colors of action bars to better match new background
- [x] Set icons for each button
- [x] Check naming conventions for views and buttons
- [x] Message colors
- [x] Send button color
- [x] Remove search bar at the top of chat log
