### ISSUE TITLE
Change Password - View

### ISSUE THREAD

**Issue by dhaist** [COSC481W-2022Fall/capstone-project-vibe#64]
**Description**
Given that the user wants to change their password, they are able to change it so that they are able to login to the app.

**Tasks**
- [ ] Text field for current password
- [ ] Forgot Password field #63 
- [ ] Text field for new password
- [ ] Text field for new password again
- [ ] Implement an Update Password button

**Acceptance Criteria**
- If the user is on the change password view, they will see fields for entering the current password and 2 fields for entering the new password to change their password for the app.

**Comment by sjiang1** [comment]
Add the following acceptance criteria:

- If the user enters the correct current password, and the new password is valid, the user’s password will be changed to the new password after clicking the Update Password button.
- Once the password is updated successfully, the user will get a message and be redirected to the settings page.
- If the user enters an incorrect current password, there will be a warning.
- If the user enters an invalid new password, there will be a warning.
- The user can click the "forgot password" button for instructions when they forget passwords.
