### ISSUE TITLE
Duplicate Conversations

### ISSUE THREAD

**Issue by dhaist** [COSC481W-2022Fall/capstone-project-vibe#89]
**Description:**
As a user, if I try to add a user that I currently have an open chat, I cannot create a new chat

**Tasks:**

- [x] Friend search has pop up message stating chat already exists
- [x] Friend search does not create new chat if chat already exists
- [x] A user cannot create a conversation with themselves

**Acceptance Criteria:**
If a user adds a username that they already have a current chat going, a pop up message will state that the chat already exists.
